[input_map]
signal_map = "../data/COM_CompMap_Compton-SZMap-nilc-ymaps_2048_R2.00.fits"
random_pointing = "../data/COM_CompMap_Compton-SZMap-nilc-ymaps_2048_R2.00_RAND_POINTING.hdf5"
smooth_fwhm = 9.6

[halo_cuts]
r_min = 0.0
r_max = 150.0
b_min = 10.0
mass_min = 1.0e12
mass_max = 1e16  # Set to a high value to ignore upper mass cut
theta_min = 10.0
theta_max = 6000 # Set to a high value to ignore upper theta cut

[mass_bins]
mass_step = 0.2
top_counts = [10, 100, 1000]
verbose_bins = true

[analysis]
which_simulation = "csiborg2"

aperture_scale = 2.0
subtract_background = true

stack_rmin = 0.1
stack_rmax = 5.0
stack_n = 100

bootstrap = 10_000
random_pool_samples = 1000
random_theta_samples = 10
seed = 42
n_jobs = -1


[halo_catalogues]

[halo_catalogues.csiborg1]
fname = "../data/csiborg1_fof.hdf5"
box_size = 677.7
omega_m = 0.307

[halo_catalogues.csiborg2]
fname = "../data/csiborg2_fof.hdf5"
nsim = 16717
box_size = 676.6
omega_m = 0.3111