[input_map]
signal_map = "../data/COM_CompMap_Compton-SZMap-nilc-ymaps_2048_R2.00.fits"
random_pointing = "../data/COM_CompMap_Compton-SZMap-nilc-ymaps_2048_R2.00_RAND_POINTING.hdf5"
smooth_fwhm = 9.6

[halo_cuts]
r_min = 0.0
r_max = 150.0
b_min = 10.0
mass_min = 1e13
mass_max = 1e16  # Set to a high value to ignore upper mass cut
theta_min = 10.0
theta_max = 6000 # Set to a high value to ignore upper theta cut

[mass_bins]
mass_step = 0.2
top_counts = [10, 50, 100]
verbose_bins = true

[analysis]
which_simulation = "csiborg2"

aperture_scale = 2.0
subtract_background = true

stack_rmin = 0.1
stack_rmax = 3.0
stack_n = 501

cutout_random_samples = 0
cutout_max_bins = 3
cutout_pixels = 301
cutout_nbins = 256
cutout_size_scale = 5
cutout_random_abs_b_min = 10

bootstrap = 10_000
random_pool_samples = 1000
random_theta_samples = 10
seed = 42
n_jobs = -1
output_hdf5 = "../data/analyse_tsz_mass_bins_results.hdf5"


[halo_catalogues]

[halo_catalogues.csiborg1]
fname = "../data/csiborg1_fof.hdf5"
box_size = 677.7
omega_m = 0.307

[halo_catalogues.csiborg2]
fname = "../data/csiborg2_fof.hdf5"
nsim = 17417
box_size = 676.6
omega_m = 0.3111
